Marten/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from food.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),

    path('blog/', include('blog.urls')),
    path('food/', include('food.urls')),
    path('user/', include('user.urls')),
    path('about/', include('about.urls')),
    path('contact', include('contact.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import BlogDetailView, BlogView

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('<slug:blog>/', BlogDetailView.as_view(), name='detail_blog'),
]

food/urls.py
from django.urls import path

from .views import CartView, FoodView, ProductsView, basket_add, basket_remove

app_name = 'food'

urlpatterns = [
    path('', FoodView.as_view(), name='food'),
    path('category/<int:category_id>/', FoodView.as_view(), name='category'),
    path('product/<slug:product>/', ProductsView.as_view(), name='product_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('basket/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

food/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Slider(models.Model):
    product = models.ForeignKey('Products', on_delete=models.CASCADE, verbose_name='Product Slider', null=True)

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = 'Slider'
        verbose_name_plural = 'Slider'


class Products(models.Model):
    images = models.FileField(upload_to='products_images/', verbose_name='Image')
    title = models.CharField(max_length=200, verbose_name='Header')
    slug = models.SlugField(unique=True, max_length=250, verbose_name='Url', db_index=True, null=True)
    description = models.TextField(verbose_name='Description', null=True)
    new_price = models.DecimalField(max_digits=4, decimal_places=2, verbose_name='New price')
    old_price = models.DecimalField(max_digits=4, decimal_places=2, blank=True, verbose_name='Old price', default=0)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Category', null=True,
                                 related_name='product_category')
    availability = models.ForeignKey('Availability', on_delete=models.CASCADE, verbose_name='Availability', null=True)
    vendor_code = models.CharField(max_length=255, verbose_name='Vendor Code', null=True)
    color = models.ManyToManyField('Color', verbose_name='Color')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Quantity', null=True)
    long_description = models.TextField(verbose_name='Full description', null=True)
    # More information
    name = models.CharField(max_length=250, verbose_name='Name', null=True)
    size = models.ManyToManyField('Size')
    length = models.ManyToManyField('Length')
    brand = models.ManyToManyField('Brand')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Products'
        verbose_name_plural = 'Products'


class ProductsImage(models.Model):
    products = models.ForeignKey(Products, default=None, on_delete=models.CASCADE)
    image = models.FileField(upload_to='images/')

    def __str__(self):
        return self.products.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Products, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user}'


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', null=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Product', null=True)
    quantity = models.PositiveIntegerField(default=0, verbose_name='Quantity')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='')

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Basket for {self.user.username} | Product {self.product.title}'

    def sum(self):
        return self.product.new_price * self.quantity


class BestProduct(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Best Product')
    end_of_discount = models.DateField(null=True)

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = 'Best Product'
        verbose_name_plural = 'Best Products'


class CommentsHome(models.Model):
    comment = models.TextField(verbose_name='Comment')
    images = models.ImageField(upload_to='comments_home_images/', verbose_name='Photo')
    full_name = models.CharField(max_length=255, verbose_name='Full name')
    profession = models.CharField(max_length=150, verbose_name='Profession')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Comment Home'
        verbose_name_plural = 'Comment Home'


class Category(models.Model):
    title = models.CharField(max_length=150, verbose_name='Category')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Brand(models.Model):
    name = models.CharField(max_length=250, verbose_name='Name Brand')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'

    def get_absolute_url(self):
        return reverse('brand', kwargs={
            'brand_id': self.id
        })


class Color(models.Model):
    name = models.CharField(max_length=250, verbose_name='Color')

    def __str__(self):
        return self.name


class Availability(models.Model):
    title = models.CharField(max_length=250, verbose_name='Availability')

    def __str__(self):
        return self.title


class Size(models.Model):
    size = models.CharField(max_length=100, verbose_name='Size')

    def __str__(self):
        return self.size


class Length(models.Model):
    length = models.CharField(max_length=100, verbose_name='length')

    def __str__(self):
        return self.length

food/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

food/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import ListView, TemplateView
from hitcount.views import HitCountDetailView

from blog.models import Blog

from .forms import CommentForm
from .models import (Basket, BestProduct, Category, Comment, CommentsHome,
                     Products, ProductsImage, Slider)


class HomeView(TemplateView):
    template_name = 'food/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data()
        context['sliders'] = Slider.objects.all()
        context['products'] = Products.objects.all().order_by('-id')[:8]
        context['best_products'] = BestProduct.objects.order_by('-id')[:1]
        context['comments_home'] = CommentsHome.objects.all()
        context['blogs'] = Blog.objects.all().order_by('-id')[:3]
        if self.request.user.is_authenticated:
            context['baskets'] = Basket.objects.filter(user=self.request.user)
        return context


class FoodView(ListView):
    model = Products
    template_name = 'food/shop-page.html'
    context_object_name = 'products'
    paginate_by = 9
    ordering = '-id'

    def get_queryset(self):
        queryset = super(FoodView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, **kwargs):
        context = super(FoodView, self).get_context_data()
        context['categories'] = Category.objects.all()
        if self.request.user.is_authenticated:
            context['baskets'] = Basket.objects.filter(user=self.request.user)
        return context


class ProductsView(HitCountDetailView):
    model = Products
    slug_url_kwarg = 'product'
    template_name = 'food/product-details.html'
    context_object_name = 'product'
    form = CommentForm

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            product_name = self.get_object()
            form.instance.user = request.user
            form.instance.post = product_name
            form.save()
            return redirect(reverse('food:product_detail', kwargs={'product': product_name.slug}))

    def get_context_data(self, *args, **kwargs):
        context = super(ProductsView, self).get_context_data()
        product_slug = self.kwargs['product']
        product = get_object_or_404(Products, slug=product_slug)
        context['photos'] = ProductsImage.objects.filter(products=product)
        context['comments'] = Comment.objects.filter(post__slug=self.kwargs['product'])
        context['form'] = self.form
        context['recent_products'] = Products.objects.all().order_by('title')[:4]
        if self.request.user.is_authenticated:
            context['baskets'] = Basket.objects.filter(user=self.request.user)
        return context


class CartView(LoginRequiredMixin, TemplateView):
    template_name = 'food/cart.html'

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data()
        context['baskets'] = Basket.objects.filter(user=self.request.user)
        return context


@login_required
def basket_add(request, product_id):
    product = Products.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        baskets = baskets.first()
        baskets.quantity += 1
        baskets.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

food/templates/food/basket_for_base.html
<div class="header-cart same-style">
    <button class="icon-cart">
        <a href="{% url 'food:cart' %}">
            <i class="icon-handbag"></i>
            <span class="count-style">{{ baskets.count }}</span>
        </a>
    </button>
</div>

food/templates/food/cart.html
{% extends 'food/base.html' %}
{% load static %}


{% block title %}
    Cart
{% endblock %}



{% block content %}
    <div class="breadcrumb-area pt-95 pb-95 bg-img"
         style="background-image:url({% static 'assets/img/banner/banner-2.jpg' %});">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <h2>Cart Page</h2>
                <ul>
                    <li><a href="{% url 'home' %}">home</a></li>
                    <li class="active">Cart Page</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- shopping-cart-area start -->
    <div class="cart-main-area pt-95 pb-100">
        <div class="container">
            <h3 class="page-title">Your cart items</h3>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="table-content table-responsive">
                            <table>
                                <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Qty</th>
                                    <th>Price</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for basket in baskets %}
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="#"><img src="{{ basket.product.images.url }}" class="w-100"></a>
                                        </td>
                                        <td class="product-name"><a href="#">{{ basket.product.title }}</a></td>
                                        <td class="product-quantity">
                                            <div class="cart-plus-minus">
                                                <input class="cart-plus-minus-box" type="text" name="qtybutton"
                                                       value="{{ basket.quantity }}">
                                            </div>
                                        </td>
                                        <td class="product-subtotal">${{ basket.sum }}</td>
                                        <td class="product-remove"><a href="{% url 'food:basket_remove' basket.id %}"><i
                                                class="ti-trash"></i></a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="cart-shiping-update-wrapper">
                                    <div class="cart-shiping-update">
                                        <a href="#">Continue Shopping</a>
                                        <button>Update Shopping Cart</button>
                                    </div>
                                    <div class="cart-clear">
                                        <a href="#">Clear Shopping Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="cart-tax">
                                <h4 class="cart-bottom-title">Estimate Shipping And Tax</h4>
                                <div class="tax-wrapper">
                                    <p>Enter your destination to get a shipping estimate.</p>
                                    <div class="tax-select-wrapper">
                                        <div class="tax-select">
                                            <label>
                                                Country
                                            </label>
                                            <select class="email s-email s-wid">
                                                <option>Bangladesh</option>
                                                <option>Albania</option>
                                                <option>Åland Islands</option>
                                                <option>Afghanistan</option>
                                                <option>Belgium</option>
                                            </select>
                                        </div>
                                        <div class="tax-select">
                                            <label>
                                                State/Province
                                            </label>
                                            <select class="email s-email s-wid">
                                                <option>Bangladesh</option>
                                                <option>Albania</option>
                                                <option>Åland Islands</option>
                                                <option>Afghanistan</option>
                                                <option>Belgium</option>
                                            </select>
                                        </div>
                                        <div class="tax-select">
                                            <label>
                                                Zip/Postal Code
                                            </label>
                                            <input type="text" placeholder="1234567">
                                        </div>
                                        <button class="cart-btn-2" type="submit">Get A Quote</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="discount-code-wrapper">
                                <h4 class="cart-bottom-title">DISCOUNT CODES</h4>
                                <div class="discount-code">
                                    <p>Enter your coupon code if you have one.</p>
                                    <form>
                                        <input type="text" required="" name="name">
                                        <button class="cart-btn-2" type="submit">Get A Quote</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12">
                            <div class="grand-totall">
                                <h5>Grand Total: ${{ baskets.total_sum }}</h5>
                                <a href="#">Proceed To Checkout</a>
                                <p>Checkout with Multiple Addresses</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

food/templates/food/shop-page.html
{% extends 'food/base.html' %}
{% load static %}

{% block title %}
    Food
{% endblock %}




{% block content %}
    <div class="breadcrumb-area pt-95 pb-95 bg-img"
         style="background-image:url({% static 'assets/img/banner/banner-2.jpg' %});">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <h2>Shop Page</h2>
                <ul>
                    <li><a href="{% url 'home' %}">home</a></li>
                    <li class="active">Shop Page</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="shop-area pt-100 pb-100 gray-bg">
        <div class="container">
            <div class="row flex-row-reverse">
                <div class="col-lg-9">
                    <div class="shop-topbar-wrapper">
                        <div class="grid-list-options">
                            <ul class="view-mode">
                                <li class="active"><a href="#product-grid" data-view="product-grid"><i
                                        class="ti-layout-grid4-alt"></i></a></li>
                                <li><a href="#product-list" data-view="product-list"><i
                                        class="ti-align-justify"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid-list-product-wrapper">
                        <div class="product-view product-grid">
                            <div class="row">
                                {% for product in products %}
                                    <div class="product-width col-lg-6 col-xl-4 col-md-6 col-sm-6">
                                        <div class="product-wrapper mb-10">
                                            <div class="product-img">
                                                <a href="{% url 'food:product_detail' product.slug %}">
                                                    <img src="{{ product.images.url }}" alt="">
                                                </a>
                                            </div>
                                            <div class="product-content">
                                                <h4>
                                                    <a href="{% url 'food:product_detail' product.slug %}">{{ product.title }}</a>
                                                </h4>
                                                <div class="product-price">
                                                    <span class="new">${{ product.new_price }} </span>
                                                    {% if product.old_price %}
                                                        <span class="old">${{ product.old_price }}</span>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="product-list-content">
                                                <h4>
                                                    <a href="{% url 'food:product_detail' product.slug %}">{{ product.title }}</a>
                                                </h4>
                                                <div class="product-price">
                                                    <span class="new">${{ product.new_price }} </span>
                                                    {% if product.old_price %}
                                                        <span class="old">${{ product.old_price }}</span>
                                                    {% endif %}
                                                </div>
                                                <p>{{ product.description|truncatewords:150 }}</p>
                                                <div class="product-list-action">
                                                    <div class="product-list-action-left">
                                                        <a class="addtocart-btn" title="Add to cart"
                                                           href="{% url 'food:basket_add' product.id %}"><i
                                                                class="ion-bag"></i> Add to cart</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            {% if is_paginated %}
                                <div class="pagination-style text-center mt-10">
                                    <ul>
                                        <li>
                                            {% if page_obj.has_previous %}
                                                <a href="?page={{ page_obj.previous_page_number }}"><i
                                                        class="icon-arrow-left"></i></a>
                                            {% endif %}
                                        </li>
                                        {% for page in page_obj.paginator.page_range %}
                                            <li>
                                                <a href="?page={{ page }}">{{ page }}</a>
                                            </li>
                                        {% endfor %}
                                        <li>
                                            {% if page_obj.has_next %}
                                                <a class="active" href="?page={{ page_obj.next_page_number }}"><i
                                                        class="icon-arrow-right"></i></a>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="shop-sidebar">
                        <div class="shop-widget">
                            <h4 class="shop-sidebar-title">Search Products</h4>
                            <div class="shop-search mt-25 mb-50">
                                <form class="shop-search-form">
                                    <input type="text" placeholder="Find a product">
                                    <button type="submit">
                                        <i class="icon-magnifier"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="shop-widget">
                            <h4 class="shop-sidebar-title">Filter By Price</h4>
                            <div class="price_filter mt-25">
                                <div id="slider-range"></div>
                                <div class="price_slider_amount">
                                    <div class="label-input">
                                        <label>price : </label>
                                        <input type="text" id="amount" name="price" placeholder="Add Your Price"/>
                                    </div>
                                    <button type="button">Filter</button>
                                </div>
                            </div>
                        </div>
                        <div class="shop-widget mt-50">
                            <a href="{% url 'food:food' %}"><h4 class="shop-sidebar-title">Food Category </h4></a>
                            <div class="shop-list-style mt-20">
                                {% for category in categories %}
                                    <ul>
                                        <li><a href="{% url 'food:category' category.id %}">{{ category.title }}</a>
                                        </li>
                                    </ul>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}